<?php
/**
 * Strattas
 * LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.strattasecomm.com/LICENSE.txt
 *
 * @category   Strattas
 * @package    Strattas_master
 * @version    1.0
 * @copyright  Copyright (c) 2012 Strattas (http://www.strattasecomm.com)
 * @license    http://www.strattasecomm.com/LICENSE.txt
 */
?>
<form method="post" action="<?php echo $this->getUrl('adminhtml/system_config/save', array('section' => 'strattasmaster'))?>"
      id="strattas_firstrun">
    <table class="form-list" cellspacing="0">
        <colgroup class="label"/>
        <colgroup class="value"/>
        <tbody>

        <tr>
            <td class="label">
                <label for="general_locale_timezone"><?php echo $this->__('I wish to be informed about')?>:</label>
            </td>
            <td class="value">


                <select name="groups[feed][fields][interests][value][]" style="width:214px" size="6" multiple="multiple"
                        id="interests">
                    <?php foreach (Mage::getModel('strattasmaster/source_updates_type')->getGridOptions() as $k => $v): ?>
                    <option selected="selected" value="<?php echo $k?>"><?php echo $this->__($v)?></option>
                    <?php endforeach;?>
                </select><br/>
                <a href="#"
                   onclick="$$($('interests').options).each(function(el){el.selected=1});return false;"><?php echo $this->__("Select all")?></a>
                /
                <a href="#"
                   onclick="$('interests').selectedIndex = -1;return false;"><?php echo $this->__("Deselect all")?></a>
            </td>
        </tr>
        <tr>
            <td class="label"></td>
            <td class="value">
                <button id="strattas-save-button" class="scalable save" style="" onclick="saveCloseMessagePopupWindow()"
                        type="button">
                    <span id="strattas-save-button-content"> <?php echo $this->__('Save &amp; Close')?></span>
                </button>
            </td>
        </tr>
        <tr>
            <td colspan="2" align="right">
                <div style="width:365px">
                    <small><?php echo $this->__("This message appears only once. At any time you can change these preferences
					from System > Configuration > Strattas extensions > Details. <br/><a href=\"%s\">Visit it now</a>", $this->getUrl('adminhtml/system_config/edit', array('section' => 'strattasmaster')))?></small>
                </div>
            </td>
        </tr>
        </tbody>
    </table>
</form>