<?php
/**
 * Strattas
 * LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.strattasecomm.com/LICENSE.txt
 *
 * @category   Strattas
 * @package    Strattas_master
 * @version    1.0
 * @copyright  Copyright (c) 2012 Strattas (http://www.strattasecomm.com)
 * @license    http://www.strattasecomm.com/LICENSE.txt
 */
?>
<div id="message-popup-window-mask" style="display:none;"></div>

<div style="position:relative;margin-left:-390px;">
    <div id="st_notif" class="notification" style="display:none;">
        <div class="head">
            <h3><?php echo $this->getHeaderText();?></h3>
            <button type="button" class="close" onclick="closeMessagePopupWindow()">
                <span><?php echo $this->getCloseText(); ?></span></button>
        </div>
        <div class="content">
            <?php echo $this->getNoticeMessageText(); ?>
        </div>
    </div>
</div>
<script>
    function showStNotificator() {
        openMessagePopupWindow();
        Effect.Appear('st_notif', { duration: 1.0 });
    }
    Event.observe(window, 'load', showStNotificator);


    function openMessagePopupWindow() {
        var height = $('html-body').getHeight();
        $('message-popup-window-mask').setStyle({'height':height + 'px'});
        toggleSelectsUnderBlock($('message-popup-window-mask'), false);
        Element.show('message-popup-window-mask');
    }

    function closeMessagePopupWindow() {
        toggleSelectsUnderBlock($('message-popup-window-mask'), true);
        Effect.Fade('st_notif', { duration: 0.5 });
        Element.hide('message-popup-window-mask');
    }


    function saveCloseMessagePopupWindow() {
        $('strattas-save-button-content').innerHTML = '<?php echo $this->__("Saving, please wait...")?>';
        $('strattas-save-button').addClassName('disabled');
        $('strattas_firstrun').request({
            onComplete: function() {
                toggleSelectsUnderBlock($('message-popup-window-mask'), true);
                Effect.Fade('st_notif', { duration: 0.5 });
                Element.hide('message-popup-window-mask');
            }
        })

    }

</script>


<?php  /*


*/
?>